<?php

namespace AppBundle\Repository;

/**
 * AlmacenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmacenRepository extends \Doctrine\ORM\EntityRepository
{
}
