<?php

namespace AppBundle\Repository;

/**
 * BolsaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BolsaRepository extends \Doctrine\ORM\EntityRepository
{
}
