<?php

namespace AppBundle\Repository;

/**
 * CentroDistribucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroDistribucionRepository extends \Doctrine\ORM\EntityRepository
{
}
