<?php

namespace AppBundle\Repository;

/**
 * RecepcionCDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepcionCDRepository extends \Doctrine\ORM\EntityRepository
{
}
