<?php

namespace AppBundle\Repository;

/**
 * ResponsableCDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableCDRepository extends \Doctrine\ORM\EntityRepository
{
}
