<?php

namespace AppBundle\Repository;

/**
 * tcMunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tcMunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
