<?php

namespace AppBundle\Repository;

/**
 * tcProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tcProvinciaRepository extends \Doctrine\ORM\EntityRepository
{
}
