<?php

namespace AppBundle\Repository;

/**
 * tcTemperaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tcTemperaturaRepository extends \Doctrine\ORM\EntityRepository
{
}
