<?php

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarUsuarioPass($id){
        $connection = $this->getEntityManager()->getConnection();

        $sql = 'SELECT password FROM usuario WHERE id = :id';
        

        $stmt = $connection->prepare($sql);

        $stmt->execute(['id'=>$id]);

        return $stmt->fetchColumn();
    }
}
