app_almacen_list:
    path:     /list
    defaults: { _controller: AppBundle:almacen:list }

app_almacen_add:
    path:     /add
    defaults: { _controller: AppBundle:almacen:add }

app_almacen_create:
    path:     /create
    defaults: { _controller: AppBundle:almacen:create }
    methods: POST

emm_almacen_redirect_add:
    path: /create
    defaults:
        _controller: AppBundle:almacen:add
        path: /almacen/add
        permanent: true

app_almacen_edit:
    path:     /edit/{id}
    defaults: { _controller: AppBundle:almacen:edit }

app_almacen_update:
    path:     /update/{id}
    defaults: { _controller: AppBundle:almacen:update }
    methods: [POST, PUT]

emm_almacen_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: AppBundle:almacen:edit
        path: /almacen/edit/{id}
        permanent: true

app_almacen_details:
    path:     /details/{id}
    defaults: { _controller: AppBundle:almacen:details }

app_almacen_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:almacen:delete }
    methods: [POST, DELETE]