app_producto_list:
    path:     /list
    defaults: { _controller: AppBundle:producto:list }

app_producto_add:
    path:     /add
    defaults: { _controller: AppBundle:producto:add }

app_producto_create:
    path:     /create
    defaults: { _controller: AppBundle:producto:create }
    methods: POST

emm_producto_redirect_add:
    path: /create
    defaults:
        _controller: AppBundle:producto:add
        path: /producto/add
        permanent: true

app_producto_edit:
    path:     /edit/{id}
    defaults: { _controller: AppBundle:producto:edit }

app_producto_update:
    path:     /update/{id}
    defaults: { _controller: AppBundle:producto:update }
    methods: [POST, PUT]

emm_producto_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: AppBundle:producto:edit
        path: /producto/edit/{id}
        permanent: true

app_producto_details:
    path:     /details/{id}
    defaults: { _controller: AppBundle:producto:details }

app_producto_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:producto:delete }
    methods: [POST, DELETE]