app_usuario_list:
    path:     /list
    defaults: { _controller: AppBundle:usuario:list }

app_usuario_buscar:
    path:     /buscar/{id}
    defaults: { _controller: AppBundle:usuario:buscarUsuario }

app_usuario_add:
    path:     /add
    defaults: { _controller: AppBundle:usuario:add }

app_usuario_create:
    path:     /create
    defaults: { _controller: AppBundle:usuario:create }
    methods: POST

emm_usuario_redirect_add:
    path: /create
    defaults:
        _controller: AppBundle:usuario:add
        path: /usuario/add
        permanent: true

app_usuario_edit:
    path:     /edit/{id}
    defaults: { _controller: AppBundle:usuario:edit }

app_usuario_update:
    path:     /update/{id}
    defaults: { _controller: AppBundle:usuario:update }
    methods: [POST, PUT]

emm_usuario_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: AppBundle:usuario:edit
        path: /usuario/edit/{id}
        permanent: true

app_usuario_details:
    path:     /details/{id}
    defaults: { _controller: AppBundle:usuario:details }

app_usuario_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:usuario:delete }
    methods: [POST, DELETE]